php_version: 7.4
disable_pipeline_maintenance: True
upgrade_commands:
  default:
    - ./vendor/bin/drush cache:rebuild
    - ./vendor/bin/drush state:set system.maintenance_mode 1 --input-format=integer --yes
    - ./vendor/bin/drush updatedb --yes
    - ./vendor/bin/drush config:import --yes
    - ./vendor/bin/drush state:set system.maintenance_mode 0 --input-format=integer --yes
    - ./vendor/bin/drush cache:rebuild
